# Collecting Data Notebook
This is a notebook aimed at collecting data from the Pro-Football-Reference website

In [193]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from urllib.request import urlopen
from bs4 import BeautifulSoup

import webbrowser as wb

pd.options.display.max_colwidth = 100

### Uselul commands
Do not run unless initialized

In [174]:
url_wr_draft_1 = 'https://www.pro-football-reference.com/play-index/draft-finder.cgi?request=1&year_min=1936&year_max=2019&type=&round_min=1&round_max=30&slot_min=1&slot_max=500&league_id=&team_id=&pos%5B%5D=WR&college_id=all&conference=any&show=all&offset=0'
html =urlopen(url_wr_draft_1)
soup = BeautifulSoup(html,'html.parser')

wb.open_new_tab(url_wr_draft_1)
table_0 = soup.find_all('table')[0]
rowx= table_0.find_all('tr')[4]
columnx = rowx.find_all('td')[3]
linkx = columnx.find_all('a')[0]
print('https://www.pro-football-reference.com'+linkx.get('href'))

https://www.pro-football-reference.com/players/S/SamuDe00.htm

### Functions

In [194]:
def tabledraft(soup):

    table_0 = soup.find_all('table')[0]

    table = pd.DataFrame(columns=['year','round','pick','player','NFL-url','pos','draft age','team',
                                  'entry year','last year','1st team pro select','pro select','weighted career AV',
                                  'years as primary starter','games', 'games started',
                                  'rushing attempts','rushing yards','rushing TD',
                                  'receiving attemps','receiving yards','receiving td',
                                  'college','link']
                         ,index=range(0,310)) # I know the size 

    row_marker = 0
    for row in table_0.find_all('tr')[2:]:
        column_marker = 0
        columns = row.find_all('td')
        for column in columns:
            if column_marker == 3:
                table.iat[row_marker,column_marker] = column.get_text()
                column_marker += 1
                table.iat[row_marker,column_marker] = 'https://www.pro-football-reference.com'+column.find_all('a')[0].get('href')
                column_marker += 1
            elif column_marker == 23:
                lista = column.find_all('a')
                if len(lista) == 0:
                    table.iat[row_marker,column_marker] = 'link is missing' 
                else:
                    table.iat[row_marker,column_marker] = lista[0].get('href') 
                    column_marker += 1
            else:
                table.iat[row_marker,column_marker] = column.get_text()
                column_marker += 1
        row_marker += 1

    table.dropna(subset=['year'],inplace=True)
    table.reset_index(drop=True)

    return table

def collegestats(soup):
    table_0 = soup.find_all('table')[0]
    table = pd.DataFrame(columns=['school','conference','class','pos','games',
                                  'receptions','yards', 'average','td',
                                 'attemps rushing','yards rushing','avg rushing','td rushing',
                                 'scrimmages','yards total','avg total','td total'],
                         index=range(0,15)) # I know the size 
    
    row_marker = 0
    for row in table_0.find_all('tr')[2:]:
        column_marker = 0
        columns = row.find_all('td')
        for column in columns:
            table.iat[row_marker,column_marker] = column.get_text()
            column_marker += 1
        row_marker += 1
    
    table.dropna(subset=['school'],inplace=True)
    table.reset_index(drop=True)    


    return table

def nflstats(soup):
    table_0 = soup.find_all('table')[1]
    table = pd.DataFrame(columns=['age','team','pos','no','game','game started',
                                 'target','receptions','yards','y/r','td','first downs','longest rec',
                                 'rec per game','yards per game','catch ratio','yards per target',
                                 'rushes','rush yards','rush td','first downs rush','longest rush',
                                 'rush yards per attempt','rush yards per game','rush attempt per games',
                                 'total touches','yards per touch','yards from scrimmage','total td','fumbles','AV'],
                         index=range(0,15)) # I know the size 
    
    row_marker = 0
    for row in table_0.find_all('tr')[2:]:
        column_marker = 0
        columns = row.find_all('td')
        for column in columns:
            table.iat[row_marker,column_marker] = column.get_text()
            column_marker += 1
        row_marker += 1
    
    table.dropna(subset=['team'],inplace=True)
    table.reset_index(drop=True)
    
    lr=table.iloc[-1]
    lrp= shiftrow(lr)
    
    table.drop(table.tail(1).index,inplace=True)
    table.loc[len(table)]=lrp

    return table

def shiftrow(row):
    return ['','','','']+row.values.tolist()[3:-1]

def

### Code

In [195]:
url_wr_draft_1 = 'https://www.pro-football-reference.com/play-index/draft-finder.cgi?request=1&year_min=1936&year_max=2019&type=&round_min=1&round_max=30&slot_min=1&slot_max=500&league_id=&team_id=&pos%5B%5D=WR&college_id=all&conference=any&show=all&offset=0'
html =urlopen(url_wr_draft_1)
soup = BeautifulSoup(html,'html.parser')

table1=tabledraft(soup)

In [196]:
table1.loc[263:265]

,year,round,pick,player,NFL-url,pos,draft age,team,entry year,last year,...,games,games started,rushing attempts,rushing yards,rushing TD,receiving attemps,receiving yards,receiving td,college,link
263,2011,1,6,Julio Jones,https://www.pro-football-reference.com/players/J/JoneJu02.htm,WR,22,ATL,2011,2019,...,119,118,18,122,0,748,11443,55,Alabama,https://www.sports-reference.com/cfb/players/julio-jones-1.html
264,2011,1,26,Jonathan Baldwin,https://www.pro-football-reference.com/players/B/BaldJo00.htm,WR,22,KAN,2011,2013,...,33,11,,,,44,607,2,Pittsburgh,https://www.sports-reference.com/cfb/players/jon-baldwin-1.html
265,2011,2,44,Titus Young,https://www.pro-football-reference.com/players/Y/YounTi00.htm,WR,22,DET,2011,2012,...,26,17,4,31,0,81,990,10,Boise St.,https://www.sports-reference.com/cfb/players/titus-young-1.html

In [197]:
julio_jones_index = table1[table1['player']=='Julio Jones'].index.tolist()

julio_jones_nfl_url = table1.loc[julio_jones_index,'link']

263    https://www.sports-reference.com/cfb/players/julio-jones-1.html
Name: link, dtype: object

In [35]:
url_julio_cfb = 'https://www.sports-reference.com/cfb/players/julio-jones-1.html'
html =urlopen(url_julio_cfb)
soup = BeautifulSoup(html,'html.parser')

table2=collegestats(soup)

table2

,school,conference,class,pos,games,receptions,yards,average,td,attemps rushing,yards rushing,avg rushing,td rushing,scrimmages,yards total,avg total,td total
0,Alabama,SEC,FR,WR,14,58,924,15.9,4,,,,,58,924,15.9,4
1,Alabama,SEC,SO,WR,13,43,596,13.9,4,2,4,2.0,0,45,600,13.3,4
2,Alabama,SEC,JR,WR,13,78,1133,14.5,7,8,135,16.9,2,86,1268,14.7,9
3,Alabama,,,,,179,2653,14.8,15,10,139,13.9,2,189,2792,14.8,17

In [155]:
url_julio_nfl = 'https://www.pro-football-reference.com/players/J/JoneJu02.htm'
html =urlopen(url_julio_nfl)
soup = BeautifulSoup(html,'html.parser')

table3=nflstats(soup)

table3

,age,team,pos,no,game,game started,target,receptions,yards,y/r,...,longest rush,rush yards per attempt,rush yards per game,rush attempt per games,total touches,yards per touch,yards from scrimmage,total td,fumbles,AV
0,22,ATL,WR,11,13,13,95,54,959,17.8,...,19,9.3,4.3,0.5,60,16.9,1015,8,1,10
1,23,ATL,WR,11,16,15,128,79,1198,15.2,...,18,5.0,1.9,0.4,85,14.4,1228,10,0,13
2,24,ATL,wr,11,5,5,59,41,580,14.1,...,7,7.0,1.4,0.2,42,14.0,587,2,2,5
3,25,ATL,WR,11,15,15,163,104,1593,15.3,...,1,1.0,0.1,0.1,105,15.2,1594,6,2,14
4,26,ATL,WR,11,16,16,203,136,1871,13.8,...,,,,,136,13.8,1871,8,3,16
5,27,ATL,WR,11,14,14,129,83,1409,17.0,...,,,,,83,17.0,1409,6,0,16
6,28,ATL,WR,11,16,16,148,88,1444,16.4,...,15,15.0,0.9,0.1,89,16.4,1459,3,0,14
7,29,ATL,WR,11,16,16,170,113,1677,14.8,...,11,6.0,0.8,0.1,115,14.7,1689,8,2,14
8,30,ATL,WR,11,8,8,74,50,712,14.2,...,1,1.0,0.1,0.1,51,14.0,713,4,1,
9,,,,,119,118,1169,748,11443,15.3,...,19,6.8,1.0,0.2,766,15.1,11565,55,11,102